### ISSUE TITLE
Clickhouse keeper is broken in bitnami chart

### ISSUE THREAD

**Issue by mleklund** [stafftastic/jitsu-chart#19]
see:

https://github.com/bitnami/charts/issues/15935

Current fix is to switch to zookeper.  The issue has been languishing for quite a while, but just noted that they are increasing the priority.  To use zookeeper set your values to `clickhouse.keeper.enable = false` and `clickhouse.zookeeper.enabled = true`.

alternatively in values.yaml:
```
clickhouse:
  keeper:
    enabled: false
  zookeeper:
    enabled: true
```
