### ISSUE TITLE
Support jitsu v2.8.0

### ISSUE THREAD

**Issue by hendrikheil** [stafftastic/jitsu-chart#46]
Jitsu just released [v2.8.0](https://github.com/jitsucom/jitsu/releases/tag/jitsu2-v2.8.0).

Notable: syncctl no longer relies on bulker and instead has bulker embedded into the image directly.

**Comment by stouch** [comment]
I got an issue with events logs clickhouse table and it might be because of this issue

https://github.com/jitsucom/jitsu/issues/1119

**Comment by stouch** [comment]
Hey, Do you know if this is going to be resolved soon? For now, I already had to setup this : https://github.com/jitsucom/jitsu/issues/1125#issuecomment-2351757178 and I think I still got issues with logs max size and some other bulker issues 

```yaml
postgresql:
  enabled: false
redis:
  enabled: false

# For Kafka rotor:
mongodb:
  enabled: true

kafka:
  extraConfig: |
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
  controller:
    replicaCount: 1

# Clickhouse is now used for Live events:
# https://github.com/jitsucom/jitsu/releases/tag/jitsu2-v2.5.0
clickhouse:
  enabled: true
  shards: 1
  replicaCount: 1
  zookeeper:
    enabled: false

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  host: <self-hosted>.<domain>.com
  tls: true

config:
  enabled: true
  # database in which we keep jitsu settings:
  databaseUrl: "postgres://newjitsu:<password>@<host>:<port>/newjitsu?schema=newjitsu"
  # cickhouse internal database, since of we got these issues:
  # - https://github.com/jitsucom/jitsu/issues/1125
  # - https://github.com/jitsucom/jitsu/issues/1119
  clickhouseDatabase: "newjitsu_metrics"

console:
  config:
    # We use internal custom user:
    seedUserEmail: "<USERNAME>"
    seedUserPassword: "<PASSWORD>"
    disableSignup: "true"
  ingress:
    enabled: false # because ingress.enabled above

ingest: 
  ingress:
    enabled: false # because ingress.enabled above
```
