### ISSUE TITLE
Customize the shards and replicaCount of clickhouse

### ISSUE THREAD

**Issue by stouch** [stafftastic/jitsu-chart#48]
I want to change the shards number and replicaCount of the clickhouse databases. I try to do : 
```yaml

clickhouse:
  enabled: true
  shards: 1
  replicaCount: 2
  
  zookeeper: 
    enabled: true
    replicaCount: 1

```

but it does not seem to affect anything. How are we suppoed to do that?

**Comment by stouch** [comment]
My bad, it works well.

**Comment by stouch** [comment]
FYI, to get only 1 kafka controller, you can do : 
```yaml
kafka:
  extraConfig: |
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
  controller:
    replicaCount: 1
```
