### ISSUE TITLE
Getting Error: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: ingress contains invalid paths: path /p.js cannot be used with pathType Exact

### ISSUE THREAD

**Issue by tedcao** [stafftastic/jitsu-chart#63]
I was trying to deploy the jitsu to Digital Ocean Kubernetes. I am new to helm and Kubrenetes.  

What I am expecting to achieve is to self host the service use connector without the 1 sync pre 24 hours limits for personal use. 

I have set up the namespace and also install the Nginx for reverse proxy. 
```
# Create namespace
kubectl create namespace ingress-nginx

# Install nginx ingress controller
helm install nginx-ingress ingress-nginx/ingress-nginx \
  --namespace ingress-nginx \
  --set controller.publishService.enabled=true
```

According to the basic configuration. 

I have created a values.yaml like following:
```
postgresql:
  auth:
    password: "1234"
mongodb:
  auth:
    passwords:
      ["1234"]
clickhouse:
  auth:
    password: "1234"

ingress:
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  host: "jitsu.tedcao.com"
  tls: true
  paths:
    - path: "/"
      pathType: Prefix

console:
  config:
    seedUserEmail: "me@example.com"
    seedUserPassword: "qwer2345"
```

After run: 
`helm install jitsu oci://registry-1.docker.io/stafftasticcharts/jitsu -f values.yaml
`
I am getting the following error message: 
```
ulled: registry-1.docker.io/stafftasticcharts/jitsu:2.2.0
Digest: sha256:2c03097da8da678569229dbb45f6517ad086faea045618280992e956e444b884
coalesce.go:237: warning: skipped value for kafka.config: Not a table.
W0116 01:58:43.327684   64620 warnings.go:70] path /p.js cannot be used with pathType Exact

Error: INSTALLATION FAILED: 1 error occurred:
        * admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: ingress contains invalid paths: path /p.js cannot be used with pathType Exact
```

I have looked into the file and find out the error message seems come from 
```
templates/ingress/yaml line 48-49
```
Should the pathType be Prefix? Or there were something wrong with my values.yaml? 

Thanks a lot!
